#pragma once

typedef enum tdn_err {
    TDN_USER_ERROR_START = -1,
    TDN_NO_ERROR = 0,
    TDN_ERROR_CHECK_FAILED = 1,
    TDN_ERROR_OUT_OF_MEMORY = 2,

    // verifier errors
    TDN_ERROR_VERIFIER_EXPECTED_NUMERIC_TYPE,
    TDN_ERROR_VERIFIER_STACK_UNEXPECTED,
    TDN_ERROR_VERIFIER_BRANCH_OUT_OF_TRY,
    TDN_ERROR_VERIFIER_BRANCH_INTO_TRY,
    TDN_ERROR_VERIFIER_BRANCH_OUT_OF_FINALLY,
    TDN_ERROR_VERIFIER_FALLTHROUGH_EXCEPTION,
    TDN_ERROR_VERIFIER_BAD_JUMP_TARGET,
    TDN_ERROR_VERIFIER_THIS_MISMATCH,
    TDN_ERROR_VERIFIER_CTOR_EXPECTED,
    TDN_ERROR_VERIFIER_CTOR_SIG,
    TDN_ERROR_VERIFIER_RETURN_VOID,
    TDN_ERROR_VERIFIER_RETURN_MISSING,
    TDN_ERROR_VERIFIER_RETURN_EMPTY,
    TDN_ERROR_VERIFIER_RETURN_FROM_TRY,
    TDN_ERROR_VERIFIER_RETURN_FROM_HANDLER,
    TDN_ERROR_VERIFIER_RETURN_FROM_FILTER,
    TDN_ERROR_VERIFIER_RETURN_PTR_TO_STACK,
    TDN_ERROR_VERIFIER_METHOD_FALLTHROUGH,
} tdn_err_t;

const char* tdn_get_error_string(tdn_err_t err);
