#include "except.h"

const char* tdn_get_error_string(tdn_err_t err) {
    if (err < 0) {
        return tdn_host_error_to_string(-err);
    }

    switch (err) {
        case TDN_NO_ERROR: return "Success";
        case TDN_ERROR_CHECK_FAILED: return "Check failed";
        case TDN_ERROR_OUT_OF_MEMORY: return "Out of memory";
        case TDN_ERROR_UNKNOWN_OPCODE: return "UNKNOWN_OPCODE";
        case TDN_ERROR_VERIFIER_METHOD_FALLTHROUGH: return "VERIFIER_METHOD_FALLTHROUGH";
        case TDN_ERROR_VERIFIER_FALLTHROUGH_EXCEPTION: return "VERIFIER_FALLTHROUGH_EXCEPTION";
        case TDN_ERROR_VERIFIER_FALLTHROUGH_INTO_HANDLER: return "VERIFIER_FALLTHROUGH_INTO_HANDLER";
        case TDN_ERROR_VERIFIER_FALLTHROUGH_INTO_FILTER: return "VERIFIER_FALLTHROUGH_INTO_FILTER";
        case TDN_ERROR_VERIFIER_LEAVE_INTO_TRY: return "VERIFIER_LEAVE_INTO_TRY";
        case TDN_ERROR_VERIFIER_LEAVE_INTO_HANDLER: return "VERIFIER_LEAVE_INTO_HANDLER";
        case TDN_ERROR_VERIFIER_LEAVE_INTO_FILTER: return "VERIFIER_LEAVE_INTO_FILTER";
        case TDN_ERROR_VERIFIER_LEAVE_OUT_OF_FILTER: return "VERIFIER_LEAVE_OUT_OF_FILTER";
        case TDN_ERROR_VERIFIER_LEAVE_OUT_OF_FINALLY: return "VERIFIER_LEAVE_OUT_OF_FINALLY";
        case TDN_ERROR_VERIFIER_LEAVE_OUT_OF_FAULT: return "VERIFIER_LEAVE_OUT_OF_FAULT";
        case TDN_ERROR_VERIFIER_RETHROW: return "VERIFIER_RETHROW";
        case TDN_ERROR_VERIFIER_ENDFINALLY: return "VERIFIER_ENDFINALLY";
        case TDN_ERROR_VERIFIER_ENDFILTER: return "VERIFIER_ENDFILTER";
        case TDN_ERROR_VERIFIER_BRANCH_INTO_TRY: return "VERIFIER_BRANCH_INTO_TRY";
        case TDN_ERROR_VERIFIER_BRANCH_INTO_HANDLER: return "VERIFIER_BRANCH_INTO_HANDLER";
        case TDN_ERROR_VERIFIER_BRANCH_INTO_FILTER: return "VERIFIER_BRANCH_INTO_FILTER";
        case TDN_ERROR_VERIFIER_BRANCH_OUT_OF_TRY: return "VERIFIER_BRANCH_OUT_OF_TRY";
        case TDN_ERROR_VERIFIER_BRANCH_OUT_OF_HANDLER: return "VERIFIER_BRANCH_OUT_OF_HANDLER";
        case TDN_ERROR_VERIFIER_BRANCH_OUT_OF_FILTER: return "VERIFIER_BRANCH_OUT_OF_FILTER";
        case TDN_ERROR_VERIFIER_BRANCH_OUT_OF_FINALLY: return "VERIFIER_BRANCH_OUT_OF_FINALLY";
        case TDN_ERROR_VERIFIER_RETURN_FROM_TRY: return "VERIFIER_RETURN_FROM_TRY";
        case TDN_ERROR_VERIFIER_RETURN_FROM_HANDLER: return "VERIFIER_RETURN_FROM_HANDLER";
        case TDN_ERROR_VERIFIER_RETURN_FROM_FILTER: return "VERIFIER_RETURN_FROM_FILTER";
        case TDN_ERROR_VERIFIER_BAD_JUMP_TARGET: return "VERIFIER_BAD_JUMP_TARGET";
        case TDN_ERROR_VERIFIER_PATH_STACK_UNEXPECTED: return "VERIFIER_PATH_STACK_UNEXPECTED";
        case TDN_ERROR_VERIFIER_PATH_STACK_DEPTH: return "VERIFIER_PATH_STACK_DEPTH";
        case TDN_ERROR_VERIFIER_THIS_UNINIT_STORE: return "VERIFIER_THIS_UNINIT_STORE";
        case TDN_ERROR_VERIFIER_THIS_UNINIT_RETURN: return "VERIFIER_THIS_UNINIT_RETURN";
        case TDN_ERROR_VERIFIER_LDFTN_CTOR: return "VERIFIER_LDFTN_CTOR";
        case TDN_ERROR_VERIFIER_STACK_UNEXPECTED: return "VERIFIER_STACK_UNEXPECTED";
        case TDN_ERROR_VERIFIER_STACK_UNEXPECTED_ARRAY_TYPE: return "VERIFIER_STACK_UNEXPECTED_ARRAY_TYPE";
        case TDN_ERROR_VERIFIER_STACK_OVERFLOW: return "VERIFIER_STACK_OVERFLOW";
        case TDN_ERROR_VERIFIER_STACK_UNDERFLOW: return "VERIFIER_STACK_UNDERFLOW";
        case TDN_ERROR_VERIFIER_UNINIT_STACK: return "VERIFIER_UNINIT_STACK";
        case TDN_ERROR_VERIFIER_EXPECTED_INTEGER_TYPE: return "VERIFIER_EXPECTED_INTEGER_TYPE";
        case TDN_ERROR_VERIFIER_EXPECTED_FLOAT_TYPE: return "VERIFIER_EXPECTED_FLOAT_TYPE";
        case TDN_ERROR_VERIFIER_EXPECTED_NUMERIC_TYPE: return "VERIFIER_EXPECTED_NUMERIC_TYPE";
        case TDN_ERROR_VERIFIER_STACK_OBJ_REF: return "VERIFIER_STACK_OBJ_REF";
        case TDN_ERROR_VERIFIER_STACK_BY_REF: return "VERIFIER_STACK_BY_REF";
        case TDN_ERROR_VERIFIER_STACK_METHOD: return "VERIFIER_STACK_METHOD";
        case TDN_ERROR_VERIFIER_UNRECOGNIZED_LOCAL_NUMBER: return "VERIFIER_UNRECOGNIZED_LOCAL_NUMBER";
        case TDN_ERROR_VERIFIER_UNRECOGNIZED_ARGUMENT_NUMBER: return "VERIFIER_UNRECOGNIZED_ARGUMENT_NUMBER";
        case TDN_ERROR_VERIFIER_EXPECTED_TYPE_TOKEN: return "VERIFIER_EXPECTED_TYPE_TOKEN";
        case TDN_ERROR_VERIFIER_TOKEN_RESOLVE: return "VERIFIER_TOKEN_RESOLVE";
        case TDN_ERROR_VERIFIER_EXPECTED_METHOD_TOKEN: return "VERIFIER_EXPECTED_METHOD_TOKEN";
        case TDN_ERROR_VERIFIER_EXPECTED_FIELD_TOKEN: return "VERIFIER_EXPECTED_FIELD_TOKEN";
        case TDN_ERROR_VERIFIER_UNVERIFIABLE: return "VERIFIER_UNVERIFIABLE";
        case TDN_ERROR_VERIFIER_STRING_OPERAND: return "VERIFIER_STRING_OPERAND";
        case TDN_ERROR_VERIFIER_RETURN_PTR_TO_STACK: return "VERIFIER_RETURN_PTR_TO_STACK";
        case TDN_ERROR_VERIFIER_RETURN_VOID: return "VERIFIER_RETURN_VOID";
        case TDN_ERROR_VERIFIER_RETURN_MISSING: return "VERIFIER_RETURN_MISSING";
        case TDN_ERROR_VERIFIER_RETURN_EMPTY: return "VERIFIER_RETURN_EMPTY";
        case TDN_ERROR_VERIFIER_EXPECTED_ARRAY: return "VERIFIER_EXPECTED_ARRAY";
        case TDN_ERROR_VERIFIER_VALUE_TYPE_EXPEXCTED: return "VERIFIER_VALUE_TYPE_EXPEXCTED";
        case TDN_ERROR_VERIFIER_TYPE_ACCESS: return "VERIFIER_TYPE_ACCESS";
        case TDN_ERROR_VERIFIER_METHOD_ACCESS: return "VERIFIER_METHOD_ACCESS";
        case TDN_ERROR_VERIFIER_FIELD_ACCESS: return "VERIFIER_FIELD_ACCESS";
        case TDN_ERROR_VERIFIER_EXPECTED_STATIC_FIELD: return "VERIFIER_EXPECTED_STATIC_FIELD";
        case TDN_ERROR_VERIFIER_INIT_ONLY: return "VERIFIER_INIT_ONLY";
        case TDN_ERROR_VERIFIER_CALLVIRT_ON_VALUE_TYPE: return "VERIFIER_CALLVIRT_ON_VALUE_TYPE";
        case TDN_ERROR_VERIFIER_CTOR_EXPECTED: return "VERIFIER_CTOR_EXPECTED";
        case TDN_ERROR_VERIFIER_CTOR_SIG: return "VERIFIER_CTOR_SIG";
        case TDN_ERROR_VERIFIER_ARRAY_BY_REF: return "VERIFIER_ARRAY_BY_REF";
        case TDN_ERROR_VERIFIER_BYYREF_OF_BYREF: return "VERIFIER_BYYREF_OF_BYREF";
        case TDN_ERROR_VERIFIER_CODE_SIZE_ZERO: return "VERIFIER_CODE_SIZE_ZERO";
        case TDN_ERROR_VERIFIER_TAIL_CALL: return "VERIFIER_TAIL_CALL";
        case TDN_ERROR_VERIFIER_TAIL_BY_REF: return "VERIFIER_TAIL_BY_REF";
        case TDN_ERROR_VERIFIER_TAIL_RET: return "VERIFIER_TAIL_RET";
        case TDN_ERROR_VERIFIER_TAIL_RET_VOID: return "VERIFIER_TAIL_RET_VOID";
        case TDN_ERROR_VERIFIER_TAIL_RET_TYPE: return "VERIFIER_TAIL_RET_TYPE";
        case TDN_ERROR_VERIFIER_TAIL_STACK_EMPTY: return "VERIFIER_TAIL_STACK_EMPTY";
        case TDN_ERROR_VERIFIER_METHOD_END: return "VERIFIER_METHOD_END";
        case TDN_ERROR_VERIFIER_BAD_BRANCH: return "VERIFIER_BAD_BRANCH";
        case TDN_ERROR_VERIFIER_VOLATILE: return "VERIFIER_VOLATILE";
        case TDN_ERROR_VERIFIER_UNALIGNED: return "VERIFIER_UNALIGNED";
        case TDN_ERROR_VERIFIER_CALL_ABSTRACT: return "VERIFIER_CALL_ABSTRACT";
        case TDN_ERROR_VERIFIER_TRY_NON_EMPTY_STACK: return "VERIFIER_TRY_NON_EMPTY_STACK";
        case TDN_ERROR_VERIFIER_FILTER_OR_CATCH_UNEXPECTED_STACK: return "VERIFIER_FILTER_OR_CATCH_UNEXPECTED_STACK";
        case TDN_ERROR_VERIFIER_FIN_OR_FAULT_NON_EMPTY_STACK: return "VERIFIER_FIN_OR_FAULT_NON_EMPTY_STACK";
        case TDN_ERROR_VERIFIER_DELEGATE_CTOR: return "VERIFIER_DELEGATE_CTOR";
        case TDN_ERROR_VERIFIER_DELEGATE_PATTERN: return "VERIFIER_DELEGATE_PATTERN";
        case TDN_ERROR_VERIFIER_BOX_BYREF: return "VERIFIER_BOX_BYREF";
        case TDN_ERROR_VERIFIER_END_FILTER_STACK: return "VERIFIER_END_FILTER_STACK";
        case TDN_ERROR_VERIFIER_DELEGATE_CTOR_SIG_I: return "VERIFIER_DELEGATE_CTOR_SIG_I";
        case TDN_ERROR_VERIFIER_DELEGATE_CTOR_SIG_O: return "VERIFIER_DELEGATE_CTOR_SIG_O";
        case TDN_ERROR_VERIFIER_CATCH_BYREF: return "VERIFIER_CATCH_BYREF";
        case TDN_ERROR_VERIFIER_THROW_OR_CATCH_ONLY_EXCEPTION_TYPE: return "VERIFIER_THROW_OR_CATCH_ONLY_EXCEPTION_TYPE";
        case TDN_ERROR_VERIFIER_LDVIRTFTN_ON_STATIC: return "VERIFIER_LDVIRTFTN_ON_STATIC";
        case TDN_ERROR_VERIFIER_CALLVIRT_ON_STATIC: return "VERIFIER_CALLVIRT_ON_STATIC";
        case TDN_ERROR_VERIFIER_INIT_LOCALS: return "VERIFIER_INIT_LOCALS";
        case TDN_ERROR_VERIFIER_CALL_CTOR: return "VERIFIER_CALL_CTOR";
        case TDN_ERROR_VERIFIER_EXPECTED_VAL_CLASS_OBJ_REF_VARIABLE: return "VERIFIER_EXPECTED_VAL_CLASS_OBJ_REF_VARIABLE";
        case TDN_ERROR_VERIFIER_READONLY: return "VERIFIER_READONLY";
        case TDN_ERROR_VERIFIER_CONSTRAINED: return "VERIFIER_CONSTRAINED";
        case TDN_ERROR_VERIFIER_CONSTRAINED_CALL_WITH_NON_BYREF_THIS: return "VERIFIER_CONSTRAINED_CALL_WITH_NON_BYREF_THIS";
        case TDN_ERROR_VERIFIER_READONLY_UNEXPECTED_CALLEE: return "VERIFIER_READONLY_UNEXPECTED_CALLEE";
        case TDN_ERROR_VERIFIER_READONLY_ILLEGAL_WRITE: return "VERIFIER_READONLY_ILLEGAL_WRITE";
        case TDN_ERROR_VERIFIER_TAIL_CALL_INSIDE_ER: return "VERIFIER_TAIL_CALL_INSIDE_ER";
        case TDN_ERROR_VERIFIER_BACKWARD_BRANCH: return "VERIFIER_BACKWARD_BRANCH";
        case TDN_ERROR_VERIFIER_NEWOBJ_ABSTRACT_CLASS: return "VERIFIER_NEWOBJ_ABSTRACT_CLASS";
        case TDN_ERROR_VERIFIER_UNMANAGED_POINTER: return "VERIFIER_UNMANAGED_POINTER";
        case TDN_ERROR_VERIFIER_LDFTN_NON_FINAL_VIRTUAL: return "VERIFIER_LDFTN_NON_FINAL_VIRTUAL";
        case TDN_ERROR_VERIFIER_THIS_MISMATCH: return "VERIFIER_THIS_MISMATCH";
        default: return "<UNKNOWN>";
    }
}


void dump_hex(const void* data, size_t size) {
    char ascii[17];
    size_t i, j;
    ascii[16] = '\0';
    for (i = 0; i < size; ++i) {
        tdn_host_printf("%02X ", ((unsigned char*)data)[i]);
        if (((unsigned char*)data)[i] >= ' ' && ((unsigned char*)data)[i] <= '~') {
            ascii[i % 16] = ((unsigned char*)data)[i];
        } else {
            ascii[i % 16] = '.';
        }
        if ((i+1) % 8 == 0 || i+1 == size) {
            tdn_host_printf(" ");
            if ((i+1) % 16 == 0) {
                tdn_host_printf("|  %s \n", ascii);
            } else if (i+1 == size) {
                ascii[(i+1) % 16] = '\0';
                if ((i+1) % 16 <= 8) {
                    tdn_host_printf(" ");
                }
                for (j = (i+1) % 16; j < 16; ++j) {
                    tdn_host_printf("   ");
                }
                tdn_host_printf("|  %s \n", ascii);
            }
        }
    }
}

void tdn_rust_panic(const char* message, size_t message_len) {
    ASSERT(false, "%.*s", message_len, message);
}
